# Barvian Realty
# ==============

url: http://barvianrealty.com
email: support@barvianrealty.com
mailto: support@barvianrealty.com?subject=Website%20Inquiry
phone: "(815) 556-8078"
tel: 8155568078
idx: http://barvianrealty.idxhome.com/homesearch/128392

social:
  facebook: https://www.facebook.com/barvianrealty

sass:
    sass_dir: static
    style: compressed

# Collections
# -----------

collections:
  agents:
    output: true

# Defaults
# --------

defaults:
  -
    scope:
      path: ""
      type: "agents"
    values:
      layout: "agent"

# Build settings
# --------------

exclude:
  - CNAME
  - static/bootstrap/site

permalink: pretty

